# Generated by Django 5.2.5 on 2025-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0002_article_image_analysis_score_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='verified_by_sources',
            field=models.CharField(default='Not available', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscribed_categories',
            field=models.CharField(default='', max_length=255),
        ),
    ]
