# Generated by Django 5.2.5 on 2025-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0003_article_source_name_article_verified_by_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
