# Generated by Django 5.2.5 on 2025-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0004_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
