# Generated by Django 5.2.5 on 2025-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0005_article_verified_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publication_date'], name='news_feed_a_publica_8b6ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-verified_at'], name='news_feed_a_verifie_2719b0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_verified'], name='news_feed_a_is_veri_a8c6ae_idx'),
        ),
    ]
