# Generated by Django 5.2.5 on 2025-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0006_article_news_feed_a_publica_8b6ad4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
